// Categories
const GET_CATEGORIES = 'GET_CATEGORIES'
// Posts
const GET_POSTS = 'GET_POSTS'
const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY'
const NEW_POST = 'NEW_POST'
const GET_POST_BY_ID = 'GET_POST_BY_ID'
const VOTE_ON_POST_BY_ID = 'VOTE_ON_POST_BY_ID'
const EDIT_POST_BY_ID = 'EDIT_POST_BY_ID'
const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID'
// Comments
const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID'
const NEW_COMMENT = 'NEW_COMMENT'
const VOTE_ON_COMMENT_BY_ID = 'VOTE_ON_COMMENT_BY_ID'
const GET_COMMENT_BY_ID = 'GET_COMMENT_BY_ID'
const GET_VOTE_ON_COMMENT = 'GET_VOTE_ON_COMMENT'
const EDIT_COMMENT_BY_ID = 'EDIT_COMMENT_BY_ID'
const DELETE_COMMENT_BY_ID = 'DELETE_COMMENT_BY_ID'

export {
    GET_CATEGORIES,
    GET_POSTS,
    GET_POSTS_BY_CATEGORY,
    NEW_POST,
    GET_POST_BY_ID,
    VOTE_ON_POST_BY_ID,
    EDIT_POST_BY_ID,
    DELETE_POST_BY_ID,
    GET_COMMENTS_BY_POST_ID,
    NEW_COMMENT,
    VOTE_ON_COMMENT_BY_ID,
    GET_COMMENT_BY_ID,
    GET_VOTE_ON_COMMENT,
    EDIT_COMMENT_BY_ID,
    DELETE_COMMENT_BY_ID,
}
